### ISSUE TITLE
Peer feedback (1) Gijs Laarman : Form input submit button please

### ISSUE THREAD

**Issue by gijslaarman** [ReiniervanLimpt/web-app-from-scratch-1920#1]
Nice busy! Looking promising so far, fetching is going easily & quick. Rendering is quick & nice that you remove the previous results.

The only remark that I will leave behind is if you can put an input type=submit in the form so I can use enter to submit my request ;).

**Comment by ReiniervanLimpt** [comment]
done thanks!
